# Usar una imagen base oficial de Node.js
FROM node:16

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar los archivos del proyecto al contenedor
COPY . .

# Instalar las dependencias del proyecto
RUN npm install

# Exponer el puerto que la aplicación va a usar
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["npm", "start"]
